// Env and runtime globals are generated by `wrangler types` into
// worker-configuration.d.ts — do not define them manually here.

// Badge values used on product catalog entries.
export type Badge = "sale" | "new" | "preview-sale" | null;

// A single product as stored in KV.
export interface Product {
  id: string;
  name: string;
  price: number;
  badge: Badge;
}

// A product enriched with inventory data from D1, as returned in API responses.
export interface ProductWithInventory extends Product {
  // null when the product has no inventory row (e.g. a newly added KV item
  // that hasn't been seeded into D1 yet).
  stock: number | null;
}

// Top-level catalog config stored alongside products in KV.
export interface CatalogConfig {
  featured_collection: string;
  currency: string;
}

// Shape of the GET /products response.
export interface ProductsResponse {
  version: string;
  environment: string;
  region: string;
  currency: string;
  featured_collection: string;
  products: ProductWithInventory[];
}

// Shape of the GET /products/:id response.
export interface ProductDetailResponse extends ProductWithInventory {
  version: string;
  environment: string;
  region: string;
}

// Shape of the GET /health response.
export interface HealthResponse {
  ok: boolean;
  version: string;
  region: string;
  timestamp: string;
}
