// Env is generated by `wrangler types` into worker-configuration.d.ts.
// CLOUDFLARE_API_TOKEN is a runtime secret (set via `wrangler secret put`)
// and must be declared here so TypeScript knows it exists on Env.
export interface WorkerEnv extends Env {
  CLOUDFLARE_API_TOKEN: string;
}

// Parameters passed when triggering a new Rollout Workflow instance.
export interface RolloutParams {
  // Name of the Worker script to roll out (e.g. "storefront-worker")
  workerName: string;
  // Version ID to promote to production
  targetVersionId: string;
  // Cloudflare account ID
  accountId: string;
  // Error rate percentage above which the health check fails (default: 2.0)
  errorThresholdPct: number;
  // Duration to soak at each percentage step, passed directly to step.sleep().
  // Must be a WorkflowSleepDuration: e.g. "2 minutes", "15 minutes", "1 hour".
  soakDuration: WorkflowSleepDuration;
  // Optional fast health-check URL for live demos, e.g. $STOREFRONT_URL/health.
  // When provided, the workflow actively probes this URL instead of relying on
  // delayed analytics data.
  healthcheckUrl?: string;
  // Number of probe requests to send when using healthcheckUrl.
  healthcheckSampleCount: number;
}

// Result returned when the Workflow completes successfully.
export interface RolloutSuccess {
  success: true;
  workerName: string;
  finalVersionId: string;
}

// Result returned when the Workflow rolls back due to a health check failure.
export interface RolloutRollback {
  success: false;
  rolledBack: true;
  workerName: string;
  revertedToVersionId: string;
  reason: string;
}

export type RolloutResult = RolloutSuccess | RolloutRollback;

// A single version entry from the Cloudflare deployments API.
export interface VersionEntry {
  version_id: string;
  percentage: number;
}

// Shape of GET /deployments response (simplified to what we need).
export interface DeploymentResponse {
  result: {
    deployments: Array<{
      versions: VersionEntry[];
    }>;
  };
}

// Health check result returned by each check step.
export interface HealthCheckResult {
  healthy: boolean;
  errorRate: number;
  requestCount: number;
  errorCount: number;
}
